theme: jekyll-theme-minimal
title: Abigail Lockhart-Calpito
![Profile picture](profile image.jpeg)
description: Abigail is a freshman at Harvard College studying engineering. She is originally from San Antonio, Texas.

[LinkedIn Profile](https://www.linkedin.com/in/abigail-lockhart-calpito-2019243/)
