theme: jekyll-theme-minimal
title: Abigail Lockhart-Calpito
logo: /p image/profile image.jpeg
description: Abigail is a freshman at Harvard College studying engineering. She is originally from San Antonio, Texas.
