theme: jekyll-theme-minimal
title: Abigail Lockhart-Calpito
logo: /p image/noice photo (3).jpg
description: Abigail is an undergraduate at Harvard College studying mechanical engineering. She is originally from San Antonio, Texas. 
site.github.is_user_page: true 
google_analytics: true
