theme: jekyll-theme-minimal
title: Abigail Lockhart-Calpito
logo: /p image/noice photo (3).jpg
description: Abigail is a freshman at Harvard College studying engineering. She is originally from San Antonio, Texas.

docs_list_title: ACME Documentation
docs:

- title: Introduction
  url: introduction.html

- title: Configuration
  url: configuration.html

- title: Deployment
  url: deployment.html
